import { DBState } from "./types";

// Datos reales de Ganadería Las Delicias — Julio 2026
export function seed(): DBState {
  const now = new Date().toISOString();

  return {
    propietarios: [
      { id: "prop-orlando", nombre: "Orlando", email: "orlando@lasdelicias.co", participacionPct: 25 },
      { id: "prop-camila", nombre: "Camila", email: "camila@lasdelicias.co", participacionPct: 25 },
      { id: "prop-nicolas", nombre: "Nicolas", email: "nicolas@lasdelicias.co", participacionPct: 25 },
      { id: "prop-rafael", nombre: "Rafael", email: "rafael@lasdelicias.co", participacionPct: 25 },
    ],
    potreros: [
      {
        id: "pot-1",
        nombre: "Lote 1",
        areaHectareas: 4,
        capacidad: 6,
        notas: "Lote actual. Se cambió el 09-jul-2026, cercado eléctrico instalado.",
        createdAt: now,
      },
      {
        id: "pot-fin-finca",
        nombre: "Fin de finca",
        areaHectareas: 3,
        capacidad: 5,
        notas: "Primer lote donde estuvieron. Corriente eléctrica llevada hasta el fin de la finca.",
        createdAt: now,
      },
    ],
    animales: [
      {
        id: "an-nube",
        nroIdentificacion: "001",
        nombre: "Nube",
        sexo: "hembra",
        raza: "Sin registrar",
        fechaNacimiento: "2024-06-01",
        fechaNacimientoAprox: true,
        categoria: "novilla",
        estado: "activo",
        potreroId: "pot-1",
        propietarioId: "prop-orlando",
        notas: "Estimación 2 años a junio 2026. Inseminada el 18-jun-2026 con semen de Urano.",
        createdAt: now,
      },
      {
        id: "an-pandora",
        nroIdentificacion: "002",
        nombre: "Pandora",
        sexo: "hembra",
        raza: "Sin registrar",
        fechaNacimiento: "2024-12-28",
        madreNombre: "Concha",
        padreNombre: "Pregonero",
        categoria: "novilla",
        estado: "activo",
        potreroId: "pot-1",
        propietarioId: "prop-camila",
        createdAt: now,
      },
      {
        id: "an-canela",
        nroIdentificacion: "003",
        nombre: "Canela",
        sexo: "hembra",
        raza: "Sin registrar",
        fechaNacimiento: "2025-06-06",
        madreNombre: "Muñeca",
        padreNombre: "Rival",
        categoria: "ternera",
        estado: "activo",
        potreroId: "pot-1",
        propietarioId: "prop-nicolas",
        createdAt: now,
      },
      {
        id: "an-zeus",
        nroIdentificacion: "200",
        nombre: "Zeus",
        sexo: "macho",
        raza: "Sin registrar",
        fechaNacimiento: "2025-06-24",
        madreNombre: "Tarcia",
        padreNombre: "Secret",
        categoria: "ternero",
        estado: "activo",
        potreroId: "pot-1",
        propietarioId: "prop-rafael",
        createdAt: now,
      },
      {
        id: "an-luna",
        nroIdentificacion: "005",
        nombre: "Luna",
        sexo: "hembra",
        raza: "Sin registrar",
        fechaNacimiento: "2025-01-01",
        fechaNacimientoAprox: true,
        categoria: "ternera",
        estado: "activo",
        potreroId: "pot-fin-finca",
        propietarioId: "prop-orlando",
        notas: "Aparece en el arriendo de 5 cabezas junto con Nube. Fecha de nacimiento y padres por confirmar.",
        createdAt: now,
      },
      {
        id: "an-nuevi",
        nroIdentificacion: "201",
        nombre: "Nuevi",
        sexo: "hembra",
        raza: "Sin registrar",
        fechaNacimiento: "2025-01-01",
        fechaNacimientoAprox: true,
        categoria: "ternera",
        estado: "activo",
        potreroId: "pot-fin-finca",
        notas: "Nuevo ingreso al hato — completar datos (sexo, edad, padres, propietario).",
        createdAt: now,
      },
    ],
    sanidad: [
      // Vacunación 05-jun-2026
      { id: "san-v-nube", animalId: "an-nube", tipo: "vacuna", producto: "Aftosa", fecha: "2026-06-05", createdAt: now },
      { id: "san-v-pandora", animalId: "an-pandora", tipo: "vacuna", producto: "Aftosa", fecha: "2026-06-05", createdAt: now },
      { id: "san-v-canela", animalId: "an-canela", tipo: "vacuna", producto: "Brucelosis", fecha: "2026-06-05", createdAt: now },
      { id: "san-v-zeus", animalId: "an-zeus", tipo: "vacuna", producto: "Aftosa", fecha: "2026-06-05", createdAt: now },

      // Purga 25-jun-2026
      { id: "san-p-nube", animalId: "an-nube", tipo: "desparasitacion", producto: "Purga", fecha: "2026-06-25", createdAt: now },
      { id: "san-p-pandora", animalId: "an-pandora", tipo: "desparasitacion", producto: "Purga", fecha: "2026-06-25", createdAt: now },
      { id: "san-p-canela", animalId: "an-canela", tipo: "desparasitacion", producto: "Purga", fecha: "2026-06-25", createdAt: now },
      { id: "san-p-zeus", animalId: "an-zeus", tipo: "desparasitacion", producto: "Purga", fecha: "2026-06-25", createdAt: now },

      // Nube: Sincronización 15-jun-2026
      {
        id: "san-nube-sinc",
        animalId: "an-nube",
        tipo: "tratamiento",
        producto: "Sincronización",
        fecha: "2026-06-15",
        costo: 15000,
        notas: "Preparación para inseminación",
        createdAt: now,
      },

      // Tratamiento moscos 11-jul-2026
      { id: "san-m-nube", animalId: "an-nube", tipo: "tratamiento", producto: "Fumigación mosco", fecha: "2026-07-11", createdAt: now },
      { id: "san-m-pandora", animalId: "an-pandora", tipo: "tratamiento", producto: "Fumigación mosco", fecha: "2026-07-11", createdAt: now },
      { id: "san-m-canela", animalId: "an-canela", tipo: "tratamiento", producto: "Fumigación mosco", fecha: "2026-07-11", createdAt: now },
      { id: "san-m-zeus", animalId: "an-zeus", tipo: "tratamiento", producto: "Fumigación mosco", fecha: "2026-07-11", createdAt: now },

      // Vitaminizado 14-jul-2026 (Over B, 8CC)
      { id: "san-vit-nube", animalId: "an-nube", tipo: "tratamiento", producto: "Vitamina Over B", dosis: "8 CC", fecha: "2026-07-14", createdAt: now },
      { id: "san-vit-pandora", animalId: "an-pandora", tipo: "tratamiento", producto: "Vitamina Over B", dosis: "8 CC", fecha: "2026-07-14", createdAt: now },
      { id: "san-vit-canela", animalId: "an-canela", tipo: "tratamiento", producto: "Vitamina Over B", dosis: "8 CC", fecha: "2026-07-14", createdAt: now },
      { id: "san-vit-zeus", animalId: "an-zeus", tipo: "tratamiento", producto: "Vitamina Over B", dosis: "8 CC", fecha: "2026-07-14", createdAt: now },

      // Pandora: Tratamiento sarna 14-jul-2026
      {
        id: "san-pandora-sarna",
        animalId: "an-pandora",
        tipo: "tratamiento",
        producto: "Tratamiento sarna",
        fecha: "2026-07-14",
        notas: "Ivermectina + crema",
        createdAt: now,
      },
    ],
    servicios: [
      {
        id: "srv-nube-urano",
        hembraId: "an-nube",
        machoIdOReferencia: "Semen Urano",
        tipo: "inseminacion",
        fechaServicio: "2026-06-18",
        resultado: "pendiente",
        fechaProbableParto: "2027-03-27", // 283 días después
        notas: "Inseminación con semen de Urano · $85.000",
        createdAt: now,
      },
    ],
    partos: [],
    pesajes: [],
    leche: [],
    gastos: [
      // Gastos fijos — arriendos
      {
        id: "gas-arr-orlando-5",
        fecha: "2026-07-15",
        categoria: "servicios",
        concepto: "Arriendo pasto 5 cab / 5 meses — Nube (Luna incl.)",
        monto: 670000,
        proveedor: "Arriendo pasto",
        pagadoPor: "prop-orlando",
        notas: "$67.000 mes/cabeza × 5 meses",
        createdAt: now,
      },
      {
        id: "gas-arr-nicolas-5",
        fecha: "2026-07-15",
        categoria: "servicios",
        concepto: "Arriendo pasto 5 cab / 5 meses — Canela / Zeus",
        monto: 670000,
        proveedor: "Arriendo pasto",
        pagadoPor: "prop-nicolas",
        notas: "$67.000 mes/cabeza × 5 meses",
        createdAt: now,
      },
      {
        id: "gas-arr-camila-5",
        fecha: "2026-07-15",
        categoria: "servicios",
        concepto: "Arriendo pasto 5 cab / 5 meses — Pandora",
        monto: 335000,
        proveedor: "Arriendo pasto",
        pagadoPor: "prop-camila",
        notas: "$67.000 mes/cabeza × 5 meses",
        createdAt: now,
      },
      {
        id: "gas-arr-orlando-4",
        fecha: "2026-07-30",
        categoria: "servicios",
        concepto: "Arriendo pasto 4 cab — Nube",
        monto: 84000,
        proveedor: "Arriendo pasto",
        pagadoPor: "prop-orlando",
        notas: "$84.000 mes/cabeza",
        createdAt: now,
      },
      {
        id: "gas-arr-camila-4",
        fecha: "2026-07-30",
        categoria: "servicios",
        concepto: "Arriendo pasto 4 cab — Pandora",
        monto: 84000,
        proveedor: "Arriendo pasto",
        pagadoPor: "prop-camila",
        notas: "$84.000 mes/cabeza",
        createdAt: now,
      },
      {
        id: "gas-arr-nicolas-4",
        fecha: "2026-07-30",
        categoria: "servicios",
        concepto: "Arriendo pasto 4 cab — Canela",
        monto: 84000,
        proveedor: "Arriendo pasto",
        pagadoPor: "prop-nicolas",
        notas: "$84.000 mes/cabeza",
        createdAt: now,
      },
      {
        id: "gas-arr-rafael-4",
        fecha: "2026-07-30",
        categoria: "servicios",
        concepto: "Arriendo pasto 4 cab — Zeus",
        monto: 84000,
        proveedor: "Arriendo pasto",
        pagadoPor: "prop-rafael",
        notas: "$84.000 mes/cabeza",
        createdAt: now,
      },

      // Gastos variables ejecutados
      {
        id: "gas-var-concentrado",
        fecha: "2026-07-11",
        categoria: "alimentacion",
        concepto: "Concentrado (Tulipán) + sal 10 kg + tratamiento mosco + 4 baldes",
        monto: 150000,
        proveedor: "Presupuestado $160.000 — real $150.000",
        participantes: ["prop-orlando", "prop-camila", "prop-nicolas", "prop-rafael"],
        notas: "Recolectado igual entre los 4 socios",
        createdAt: now,
      },
      {
        id: "gas-var-corriente",
        fecha: "2026-07-11",
        categoria: "infraestructura",
        concepto: "Instalación cerca eléctrica",
        monto: 79000,
        proveedor: "1 lb puntillas, 200 mt cinta, 1 pq aisladores",
        participantes: ["prop-orlando", "prop-camila", "prop-nicolas", "prop-rafael"],
        notas: "Presupuesto $80.000",
        createdAt: now,
      },
      {
        id: "gas-var-vitamina",
        fecha: "2026-07-14",
        categoria: "sanidad",
        concepto: "Vitamina Over B + jeringas",
        monto: 46500,
        proveedor: "Aplicado 8cc / cabeza",
        participantes: ["prop-orlando", "prop-camila", "prop-nicolas", "prop-rafael"],
        createdAt: now,
      },
      {
        id: "gas-nube-sinc",
        fecha: "2026-06-15",
        categoria: "sanidad",
        concepto: "Tratamiento sincronización — Nube",
        monto: 15000,
        animalId: "an-nube",
        notas: "Preparación para inseminación",
        createdAt: now,
      },
      {
        id: "gas-nube-insem",
        fecha: "2026-06-18",
        categoria: "sanidad",
        concepto: "Inseminación con semen de Urano — Nube",
        monto: 85000,
        animalId: "an-nube",
        proveedor: "Semen Urano",
        createdAt: now,
      },
    ],
    ingresos: [],
    tareas: [
      // ─── Cronograma ejecutado julio 2026 ────────────────────────────
      {
        id: "tar-crono-0704",
        titulo: "Suministro de agua y forraje",
        fecha: "2026-07-04",
        prioridad: "media",
        categoria: "alimentacion",
        completada: true,
        completadaFecha: "2026-07-04T18:00:00.000Z",
        asignadoAId: "prop-orlando",
        createdAt: now,
      },
      {
        id: "tar-crono-0707",
        titulo: "Suministro de agua y forraje",
        fecha: "2026-07-07",
        prioridad: "media",
        categoria: "alimentacion",
        completada: true,
        completadaFecha: "2026-07-07T18:00:00.000Z",
        asignadoAId: "prop-nicolas",
        createdAt: now,
      },
      {
        id: "tar-crono-0709",
        titulo: "Suministro de agua y forraje + cambio de lote",
        descripcion: "Cambio de lote, se mueve el agua y se pone corriente.",
        fecha: "2026-07-09",
        prioridad: "media",
        categoria: "manejo",
        completada: true,
        completadaFecha: "2026-07-09T18:00:00.000Z",
        asignadoAId: "prop-orlando",
        potreroId: "pot-1",
        createdAt: now,
      },
      {
        id: "tar-crono-0711",
        titulo: "Rotación de pasturas + cercado eléctrico",
        descripcion:
          "Se llevó la corriente hasta el fin de la finca primer lote. Inicio de concentrado 2 kg por ternero + sal. Fumigación contra el mosco. Se puso pasto en el lote actual.",
        fecha: "2026-07-11",
        prioridad: "alta",
        categoria: "manejo",
        completada: true,
        completadaFecha: "2026-07-11T18:00:00.000Z",
        asignadoAId: "prop-orlando",
        potreroId: "pot-fin-finca",
        createdAt: now,
      },
      {
        id: "tar-crono-0714-rot",
        titulo: "Rotación + traslado agua + concentrado + sal",
        descripcion: "Inicio nuevo Lote 1.",
        fecha: "2026-07-14",
        prioridad: "alta",
        categoria: "manejo",
        completada: true,
        completadaFecha: "2026-07-14T18:00:00.000Z",
        asignadoAId: "prop-orlando",
        potreroId: "pot-1",
        createdAt: now,
      },
      {
        id: "tar-crono-0714-vit",
        titulo: "Vitaminizado + tratamiento a Pandora",
        descripcion: "Ivermectina + crema. Vitamina Over B 8 CC / cabeza.",
        fecha: "2026-07-14",
        prioridad: "alta",
        categoria: "sanidad",
        completada: true,
        completadaFecha: "2026-07-14T18:00:00.000Z",
        asignadoAId: "prop-camila",
        animalId: "an-pandora",
        createdAt: now,
      },
      {
        id: "tar-crono-0717",
        titulo: "Suministro de agua y forraje + concentrado",
        fecha: "2026-07-17",
        prioridad: "media",
        categoria: "alimentacion",
        completada: true,
        completadaFecha: "2026-07-17T18:00:00.000Z",
        asignadoAId: "prop-camila",
        createdAt: now,
      },
      {
        id: "tar-crono-0721",
        titulo: "Suministro de agua y forraje + concentrado",
        fecha: "2026-07-21",
        prioridad: "media",
        categoria: "alimentacion",
        completada: true,
        completadaFecha: "2026-07-21T12:00:00.000Z",
        asignadoAId: "prop-nicolas",
        createdAt: now,
      },
      // ─── Pendientes ─────────────────────────────────────────────────
      {
        id: "tar-rotar-lote1",
        titulo: "Rotar potrero — mover a Fin de finca",
        descripcion: "El Lote 1 lleva casi un mes con las 4 cabezas. Revisar pasto antes de mover.",
        fecha: "2026-07-25",
        prioridad: "media",
        categoria: "manejo",
        completada: false,
        potreroId: "pot-1",
        createdAt: now,
      },
      {
        id: "tar-diag-nube",
        titulo: "Diagnóstico de preñez — Nube",
        descripcion: "Palpar / ecografía a los 45 días post-inseminación (18-jun).",
        fecha: "2026-08-02",
        prioridad: "alta",
        categoria: "reproduccion",
        completada: false,
        animalId: "an-nube",
        createdAt: now,
      },
      {
        id: "tar-comprar-sal",
        titulo: "Comprar sal mineralizada",
        descripcion: "Quedan menos de 3 kg. Traer bulto nuevo la próxima vez.",
        fecha: "2026-07-22",
        prioridad: "baja",
        categoria: "alimentacion",
        completada: false,
        createdAt: now,
      },
    ],
    insumos: [
      {
        id: "ins-sal",
        nombre: "Sal mineralizada",
        categoria: "alimentacion",
        unidad: "kg",
        stock: 3,
        minimo: 10,
        costoUnitario: 4500,
        proveedor: "Agroinsumos local",
        createdAt: now,
      },
      {
        id: "ins-concentrado",
        nombre: "Concentrado Tulipán",
        categoria: "alimentacion",
        unidad: "bulto",
        stock: 1,
        minimo: 2,
        costoUnitario: 95000,
        createdAt: now,
      },
      {
        id: "ins-vitamina",
        nombre: "Vitamina Over B",
        categoria: "sanidad",
        unidad: "ml",
        stock: 68,
        minimo: 50,
        costoUnitario: 350,
        notas: "8 CC por cabeza. Sirve para las 4 vacas.",
        createdAt: now,
      },
      {
        id: "ins-cinta",
        nombre: "Cinta eléctrica 200 m",
        categoria: "infraestructura",
        unidad: "rollo",
        stock: 0,
        minimo: 1,
        costoUnitario: 45000,
        createdAt: now,
      },
    ],
    movimientosInsumo: [
      {
        id: "mov-ini-sal",
        insumoId: "ins-sal",
        fecha: "2026-07-11",
        tipo: "entrada",
        cantidad: 10,
        costoTotal: 45000,
        motivo: "Compra inicial (10 kg junto con concentrado)",
        createdAt: now,
      },
      {
        id: "mov-uso-sal",
        insumoId: "ins-sal",
        fecha: "2026-07-18",
        tipo: "salida",
        cantidad: 7,
        motivo: "Consumo en Lote 1 (semana)",
        potreroId: "pot-1",
        createdAt: now,
      },
      {
        id: "mov-ini-vit",
        insumoId: "ins-vitamina",
        fecha: "2026-07-14",
        tipo: "entrada",
        cantidad: 100,
        costoTotal: 35000,
        motivo: "Compra Over B",
        createdAt: now,
      },
      {
        id: "mov-uso-vit",
        insumoId: "ins-vitamina",
        fecha: "2026-07-14",
        tipo: "salida",
        cantidad: 32,
        motivo: "Aplicado 8 CC × 4 cabezas",
        createdAt: now,
      },
    ],
  };
}
